### ISSUE TITLE
Setting speed rather than position targets

### ISSUE THREAD

**Issue by lynaghk** [idubrov/stepgen#2]
Hi @idubrov,

This looks like a really cool crate, thanks for making it!

I particularly like how small the API is and that it returns plain numbers, which means I can use it with my microcontroller hardware timers.

Do you have any suggestions for how to use the crate with target speeds rather than target step positions?
That is, rather than trying to smoothly accelerate and decelerate to reach an absolute step position, I'd like to smoothly accelerate from the current speed to a target speed given by, e.g., a joystick.

From my first quick reading of the code, it seems like everything is oriented around moving to a desired absolute step position, but in my use case I don't have that.

Also, can you say anything about what motivated you to write this library?
It's clear you put a lot of time in, so I'm curious to hear any backstory about cool robots or CNC machines =)

**Comment by idubrov** [comment]
Thank you for your kind words!

I built this crate for my X2 mini-mill auto-feed project, which you can find [here](https://github.com/idubrov/x2-feed). The piece that controls the stepper motor is [this file](https://github.com/idubrov/x2-feed/blob/master/src/stepper.rs).

I haven't worked on this project for a long time, unfortunately, so I don't ever remember all the features... I'm pretty sure the main feature was exactly to run at a given speed, for smooth cutter movement. Assembled project you can see here: https://www.homemodelenginemachinist.com/threads/redoing-stepper-motor-power-feed-for-x2.26832/ 

I also built a second one for my mini-lathe, it can run feed proportional to the RPM. I was also planning to make a feedback loop in a way that it can cut threads on a lathe (I don't have gears on my lather, which are typically used to cut threads), but never finished that project.

This particular crate was built in mind with two use-cases: moving to a target position and also moving to a target speed. I think, for running with a constant speed I was using "infinite" (large numbers stepper would never reach) positions for the target.

**Comment by lynaghk** [comment]
That's a nice looking lil' mill!
I particularly like the manufacturer's "do not use capacitor as handle" sticker.

I considered the "infinite" target position hack and it seems like there are a few more that would be needed as well (since, e.g., the target speed [cannot be set to 0](https://github.com/idubrov/stepgen/blob/0b95af435b88b1d6cac426e67df2b54c3195a3a5/src/lib.rs#L222-L225)).
I'll try it out, take a closer read of the underlying algorithm, and look at other options and writeup my findings in this issue in case anyone else runs into this.

**Comment by idubrov** [comment]
Yeah, I think, I set target to current position (or to 0) to stop. It's really only for ramp-up-coast-ramp-down to target in one direction. More complex cases require some extra math to do (which I do in `x2-feed` project).

**Comment by lynaghk** [comment]
I did some more digging and decided to use a hardware-timer based approach ([described here](http://www.ti.com/lit/SLYT482)).
Essentially, use a hardware timer to emit pulses at a "current speed" and then have a second timer (hardware or software [timing queue](https://rtfm.rs/0.5/book/en/by-example/timer-queue.html)) adjust the speed (i.e., auto reload register) of the former.
This allows me to do a very simple speed-based control algorithm in that second timer (basically, add/subtract max acceleration to adjust current speed in the direction of the desired speed)

Thanks again for the discussion!
