### ISSUE TITLE
Default branch on codecov.io is seemingly incorrect

### ISSUE THREAD

**Issue by Tommypop2** [idubrov/stepgen#5]
When navigating to [codecov.io](https://app.codecov.io/gh/idubrov/stepgen), the default branch appears to be `master`. I think this is probably the cause of the README coverage badge displaying "unknown".

CircleCI also seems to be using the `master` branch instead of main.

**Comment by idubrov** [comment]
Removed the badges. Couldn't make codecov one to work and not using CircleCI anymore.
