### ISSUE TITLE
URL in README is 404

### ISSUE THREAD

**Issue by emmiebyte** [idubrov/stepgen#6]
The URL "[Generate stepper-motor speed pro les in real time](http://www.embedded.com/design/mcus-processors-and-socs/4006438/Generate-stepper-motor-speed-profiles-in-real-time)" goes to a 404.
A possible alternative is to change the link to an archived version (note that the actual link is also different, because it forwarded me and I used the actual location to save others the wait time):
[Generate stepper-motor speed profiles in real time](https://web.archive.org/web/20240514211308/https://www.embedded.com/generate-stepper-motor-speed-profiles-in-real-time/)

**Comment by idubrov** [comment]
Updated the link to archived version. Also, seems like I saved PDF in the `docs/`. I wonder if I should link to it instead.
